### ISSUE TITLE
[FEATURE] Packages upgrade

### ISSUE THREAD

**Issue by InspectlyMads** [vadrian89/html-editor-plus#7]
**Is your feature request related to a problem? Please describe.**
I need the new version of file_picker (file_picker: ^8.0.3)

**Describe the solution you'd like**
Please consider the possibility of upgrading packages - More specifically the file_picker package

**Comment by kydemy-fran** [comment]
I've created a PR for this:
https://github.com/vadrian89/html-editor-plus/pull/9

Hopefully it will be merged. If you can use my fork/branch in the meantime:
```yaml
  html_editor_plus:
    git:
      url: https://github.com/kydemy-fran/html-editor-plus
      ref: updated_dependencies
```
